### ISSUE TITLE
Repo Gathering errors out with "Forbidden": 500 Error Code.

### ISSUE THREAD

**Issue by J-Farmer** [mkitzmann/awwesome#17]
Hello! I'm trying to selfhost awwesome, but keep running into a strange issue. The program looks like it is downloading repos from Github, but eventually errors out with Error: "Forbidden" and Error: 500. Not sure what exactly is causing it.

Running this through docker compose on Windows 11 with Docker Desktop. Compose file is directly from the Github README.

Full log below:

```
2023-12-15 17:50:06 
2023-12-15 17:50:07 src/lib/fetch-github.ts (1:9) "GithubQueryResult" is not exported by "src/lib/types/types.ts", imported by "src/lib/fetch-github.ts".
2023-12-15 17:50:07 src/lib/fetch-github.ts (1:28) "GithubRepo" is not exported by "src/lib/types/types.ts", imported by "src/lib/fetch-github.ts".
2023-12-15 17:50:07 src/lib/fetch-github.ts (1:40) "Project" is not exported by "src/lib/types/types.ts", imported by "src/lib/fetch-github.ts".
2023-12-15 17:50:14 
2023-12-15 17:50:05 
2023-12-15 17:50:05 > awwesome@0.7.1 build
2023-12-15 17:50:05 > vite build
2023-12-15 17:50:05 
2023-12-15 17:50:06 vite v4.4.8 building SSR bundle for production...
2023-12-15 17:50:06 transforming...
2023-12-15 17:50:07 ✓ 101 modules transformed.
2023-12-15 17:50:07 rendering chunks...
2023-12-15 17:50:07 creating entries function
2023-12-15 17:50:14 vite v4.4.8 building for production...
2023-12-15 17:50:14 transforming...
2023-12-15 17:50:15 ✓ 90 modules transformed.
2023-12-15 17:50:15 rendering chunks...
2023-12-15 17:50:15 computing gzip size...
2023-12-15 17:50:15 .svelte-kit/output/client/_app/version.json                              0.03 kB │ gzip:  0.05 kB
2023-12-15 17:50:15 .svelte-kit/output/client/vite-manifest.json                             2.70 kB │ gzip:  0.49 kB
2023-12-15 17:50:15 .svelte-kit/output/client/_app/immutable/assets/0.2cfb8f6d.css          11.67 kB │ gzip:  3.06 kB
2023-12-15 17:50:15 .svelte-kit/output/client/_app/immutable/chunks/each.e59479a4.js         0.09 kB │ gzip:  0.10 kB
2023-12-15 17:50:15 .svelte-kit/output/client/_app/immutable/chunks/stores.ff715d12.js       0.30 kB │ gzip:  0.18 kB
2023-12-15 17:50:15 .svelte-kit/output/client/_app/immutable/nodes/1.396ee572.js             0.84 kB │ gzip:  0.52 kB
2023-12-15 17:50:15 .svelte-kit/output/client/_app/immutable/chunks/index.08fbc02c.js        2.39 kB │ gzip:  1.24 kB
2023-12-15 17:50:15 .svelte-kit/output/client/_app/immutable/chunks/singletons.dd1125c7.js   2.91 kB │ gzip:  1.49 kB
2023-12-15 17:50:15 .svelte-kit/output/client/_app/immutable/entry/app.71aa22a8.js           6.01 kB │ gzip:  2.35 kB
2023-12-15 17:50:15 .svelte-kit/output/client/_app/immutable/chunks/scheduler.8ad5346b.js    8.11 kB │ gzip:  3.21 kB
2023-12-15 17:50:15 .svelte-kit/output/client/_app/immutable/entry/start.84793446.js        24.06 kB │ gzip:  9.56 kB
2023-12-15 17:50:15 .svelte-kit/output/client/_app/immutable/nodes/0.c2d02ee5.js            26.57 kB │ gzip:  5.31 kB
2023-12-15 17:50:15 .svelte-kit/output/client/_app/immutable/nodes/2.c6479aba.js            62.13 kB │ gzip: 21.62 kB
2023-12-15 17:50:15 ✓ built in 1.03s
2023-12-15 17:50:16 creating load function, category:  
2023-12-15 17:50:22 loaded 1445 projects from Awesome Selfhosted and Sysadmin in 6542.791224002838ms
2023-12-15 17:50:29 Github Repos total: 1222
2023-12-15 17:50:33 Repos: 19, Github API cost: 1, remaining: 4938
2023-12-15 17:50:37 Repos: 20, Github API cost: 1, remaining: 4937
2023-12-15 17:50:41 Repos: 19, Github API cost: 1, remaining: 4936
2023-12-15 17:50:45 Repos: 19, Github API cost: 1, remaining: 4935
2023-12-15 17:50:50 Repos: 20, Github API cost: 1, remaining: 4934
2023-12-15 17:50:54 Repos: 18, Github API cost: 1, remaining: 4933
2023-12-15 17:50:58 Repos: 19, Github API cost: 1, remaining: 4932
2023-12-15 17:51:02 Repos: 18, Github API cost: 1, remaining: 4931
2023-12-15 17:51:05 Repos: 20, Github API cost: 1, remaining: 4930
2023-12-15 17:51:10 Repos: 19, Github API cost: 1, remaining: 4929
2023-12-15 17:51:14 Repos: 18, Github API cost: 1, remaining: 4928
2023-12-15 17:51:17 Repos: 16, Github API cost: 1, remaining: 4927
2023-12-15 17:51:22 Repos: 20, Github API cost: 1, remaining: 4926
2023-12-15 17:51:26 Repos: 20, Github API cost: 1, remaining: 4925
2023-12-15 17:51:30 Repos: 20, Github API cost: 1, remaining: 4924
2023-12-15 17:51:33 Repos: 17, Github API cost: 1, remaining: 4923
2023-12-15 17:51:37 Repos: 19, Github API cost: 1, remaining: 4922
2023-12-15 17:51:41 Repos: 20, Github API cost: 1, remaining: 4921
2023-12-15 17:51:45 Repos: 16, Github API cost: 1, remaining: 4920
2023-12-15 17:51:49 Repos: 19, Github API cost: 1, remaining: 4919
2023-12-15 17:51:53 Repos: 18, Github API cost: 1, remaining: 4918
2023-12-15 17:51:56 Repos: 18, Github API cost: 1, remaining: 4917
2023-12-15 17:52:01 Repos: 20, Github API cost: 1, remaining: 4916
2023-12-15 17:52:05 Repos: 19, Github API cost: 1, remaining: 4915
2023-12-15 17:52:10 Repos: 19, Github API cost: 1, remaining: 4914
2023-12-15 17:52:13 Repos: 18, Github API cost: 1, remaining: 4913
2023-12-15 17:52:17 Repos: 19, Github API cost: 1, remaining: 4912
2023-12-15 17:52:21 Repos: 18, Github API cost: 1, remaining: 4911
2023-12-15 17:52:26 Repos: 20, Github API cost: 1, remaining: 4910
2023-12-15 17:52:29 Repos: 19, Github API cost: 1, remaining: 4909
2023-12-15 17:52:34 Repos: 20, Github API cost: 1, remaining: 4908
2023-12-15 17:52:38 Repos: 18, Github API cost: 1, remaining: 4907
2023-12-15 17:52:44 Repos: 20, Github API cost: 1, remaining: 4906
2023-12-15 17:52:48 Repos: 17, Github API cost: 1, remaining: 4905
2023-12-15 17:52:52 Repos: 20, Github API cost: 1, remaining: 4904
2023-12-15 17:52:56 Repos: 19, Github API cost: 1, remaining: 4903
2023-12-15 17:53:00 Repos: 19, Github API cost: 1, remaining: 4902
2023-12-15 17:53:05 Repos: 19, Github API cost: 1, remaining: 4901
2023-12-15 17:53:09 Repos: 20, Github API cost: 1, remaining: 4900
2023-12-15 17:53:13 Repos: 20, Github API cost: 1, remaining: 4899
2023-12-15 17:53:17 Repos: 20, Github API cost: 1, remaining: 4898
2023-12-15 17:53:22 Repos: 20, Github API cost: 1, remaining: 4897
2023-12-15 17:53:26 Repos: 20, Github API cost: 1, remaining: 4896
2023-12-15 17:53:29 Repos: 17, Github API cost: 1, remaining: 4895
2023-12-15 17:53:33 Repos: 20, Github API cost: 1, remaining: 4894
2023-12-15 17:53:33 Error: "Forbidden"
2023-12-15 17:53:33     at fetchRepoInfoFromGithub (file:///usr/src/app/.svelte-kit/output/server/entries/pages/_...category_/_page.server.ts.js:258:11)
2023-12-15 17:53:33     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-12-15 17:53:33     at async fetchAllGithubRepositories (file:///usr/src/app/.svelte-kit/output/server/entries/pages/_...category_/_page.server.ts.js:218:20)
2023-12-15 17:53:33     at async load (file:///usr/src/app/.svelte-kit/output/server/entries/pages/_...category_/_page.server.ts.js:330:12)
2023-12-15 17:53:33     at async load_server_data (file:///usr/src/app/.svelte-kit/output/server/index.js:646:18)
2023-12-15 17:53:33     at async file:///usr/src/app/.svelte-kit/output/server/index.js:2009:18
2023-12-15 17:53:33 Error: "Forbidden"
2023-12-15 17:53:33     at fetchRepoInfoFromGithub (file:///usr/src/app/.svelte-kit/output/server/entries/pages/_...category_/_page.server.ts.js:258:11)
2023-12-15 17:53:33     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-12-15 17:53:33     at async fetchAllGithubRepositories (file:///usr/src/app/.svelte-kit/output/server/entries/pages/_...category_/_page.server.ts.js:218:20)
2023-12-15 17:53:33     at async load (file:///usr/src/app/.svelte-kit/output/server/entries/pages/_...category_/_page.server.ts.js:330:12)
2023-12-15 17:53:33     at async load_server_data (file:///usr/src/app/.svelte-kit/output/server/index.js:646:18)
2023-12-15 17:53:33     at async file:///usr/src/app/.svelte-kit/output/server/index.js:2009:18
2023-12-15 17:53:33 creating load function, category:  analytics
2023-12-15 17:53:33 
2023-12-15 17:53:33 node:internal/event_target:1088
2023-12-15 17:53:33   process.nextTick(() => { throw err; });
2023-12-15 17:53:33                            ^
2023-12-15 17:53:33 Error: 500 /
2023-12-15 17:53:33 To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
2023-12-15 17:53:33     at file:///usr/src/app/node_modules/@sveltejs/kit/src/core/config/options.js:212:13
2023-12-15 17:53:33     at file:///usr/src/app/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:64:25
2023-12-15 17:53:33     at save (file:///usr/src/app/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:403:4)
2023-12-15 17:53:33     at visit (file:///usr/src/app/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:236:3)
2023-12-15 17:53:33 Emitted 'error' event on Worker instance at:
2023-12-15 17:53:33     at [kOnErrorMessage] (node:internal/worker:326:10)
2023-12-15 17:53:33     at [kOnMessage] (node:internal/worker:337:37)
2023-12-15 17:53:33     at MessagePort.<anonymous> (node:internal/worker:232:57)
2023-12-15 17:53:33     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)
2023-12-15 17:53:33     at exports.emitMessage (node:internal/per_context/messageport:23:28)
2023-12-15 17:53:33 
2023-12-15 17:53:33 Node.js v20.10.0
2023-12-15 17:53:33 npm notice 
2023-12-15 17:53:33 npm notice New patch version of npm available! 10.2.3 -> 10.2.5
2023-12-15 17:53:33 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.5>
2023-12-15 17:53:33 npm notice Run `npm install -g npm@10.2.5` to update!
2023-12-15 17:53:33 npm notice 
```

**Comment by mkitzmann** [comment]
I had this issue a while back and thought I fixed it in https://github.com/mkitzmann/awwesome/commit/965436583d1fe9dcea6857e976463fd66cb9e5ad

What I think is happening is that there are too many requests in a short time so Github rate limit is kicking in.
Initially I used Promise.all to speed up the build process, but then I went back to sequentially handling the request so this does not happen. Maybe your machine is too fast and thus there are still too many requests.

**Comment by J-Farmer** [comment]
Interesting. As a test, I rate-limited my computer to 100 Mbps, and the same issue occurred.

**Comment by mkitzmann** [comment]
Just to be sure, did you create a fine-grained personal access token as described here https://github.com/mkitzmann/awwesome#personal-access-token ?

**Comment by J-Farmer** [comment]
Yep, I used a fine-grained personal access token.

**Comment by MisterDeee** [comment]
I'm seeing the same error here. I am using a fine-grained PAT as well.

Partial log:

```awwesome  | loaded 1442 projects from Awesome Selfhosted and Sysadmin in 12887.901942014694ms
awwesome  | Github Repos total: 1215
awwesome  | Repos: 19, Github API cost: 1, remaining: 4815
awwesome  | Repos: 20, Github API cost: 1, remaining: 4814
awwesome  | Repos: 19, Github API cost: 1, remaining: 4813
awwesome  | Repos: 19, Github API cost: 1, remaining: 4812
awwesome  | Repos: 20, Github API cost: 1, remaining: 4811
awwesome  | Repos: 18, Github API cost: 1, remaining: 4810
awwesome  | Repos: 19, Github API cost: 1, remaining: 4809
awwesome  | Repos: 18, Github API cost: 1, remaining: 4808
awwesome  | Repos: 20, Github API cost: 1, remaining: 4807
awwesome  | Repos: 19, Github API cost: 1, remaining: 4806
awwesome  | Repos: 15, Github API cost: 1, remaining: 4805
awwesome  | Repos: 19, Github API cost: 1, remaining: 4804
awwesome  | Repos: 20, Github API cost: 1, remaining: 4803
awwesome  | Repos: 20, Github API cost: 1, remaining: 4802
awwesome  | Repos: 19, Github API cost: 1, remaining: 4801
awwesome  | Error: "Forbidden"
awwesome  |     at fetchRepoInfoFromGithub (file:///usr/src/app/.svelte-kit/output/server/entries/pages/_...category_/_page.server.ts.js:258:11)
awwesome  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
awwesome  |     at async fetchAllGithubRepositories (file:///usr/src/app/.svelte-kit/output/server/entries/pages/_...category_/_page.server.ts.js:218:20)
awwesome  |     at async load (file:///usr/src/app/.svelte-kit/output/server/entries/pages/_...category_/_page.server.ts.js:330:12)
awwesome  |     at async load_server_data (file:///usr/src/app/.svelte-kit/output/server/index.js:646:18)
awwesome  |     at async file:///usr/src/app/.svelte-kit/output/server/index.js:2009:18
awwesome  | Error: "Forbidden"
awwesome  |     at fetchRepoInfoFromGithub (file:///usr/src/app/.svelte-kit/output/server/entries/pages/_...category_/_page.server.ts.js:258:11)
awwesome  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
awwesome  |     at async fetchAllGithubRepositories (file:///usr/src/app/.svelte-kit/output/server/entries/pages/_...category_/_page.server.ts.js:218:20)
awwesome  |     at async load (file:///usr/src/app/.svelte-kit/output/server/entries/pages/_...category_/_page.server.ts.js:330:12)
awwesome  |     at async load_server_data (file:///usr/src/app/.svelte-kit/output/server/index.js:646:18)
awwesome  |     at async file:///usr/src/app/.svelte-kit/output/server/index.js:2009:18
awwesome  | creating load function, category:  analytics
awwesome  | 
awwesome  | node:internal/event_target:1088
awwesome  |   process.nextTick(() => { throw err; });
awwesome  |                            ^
awwesome  | Error: 500 /
awwesome  | To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
awwesome  |     at file:///usr/src/app/node_modules/@sveltejs/kit/src/core/config/options.js:212:13
awwesome  |     at file:///usr/src/app/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:64:25
awwesome  |     at save (file:///usr/src/app/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:403:4)
awwesome  |     at visit (file:///usr/src/app/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:236:3)
awwesome  | Emitted 'error' event on Worker instance at:
awwesome  |     at [kOnErrorMessage] (node:internal/worker:326:10)
awwesome  |     at [kOnMessage] (node:internal/worker:337:37)
awwesome  |     at MessagePort.<anonymous> (node:internal/worker:232:57)
awwesome  |     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)
awwesome  |     at exports.emitMessage (node:internal/per_context/messageport:23:28)
awwesome  | 
awwesome  | Node.js v20.10.0
awwesome  | npm notice 
awwesome  | npm notice New patch version of npm available! 10.2.3 -> 10.2.5
awwesome  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.5>
awwesome  | npm notice Run `npm install -g npm@10.2.5` to update!
awwesome  | npm notice 
awwesome exited with code 1
```

**Comment by mkitzmann** [comment]
I have added a `requestDelay` setting in config.ts which will delay each request to GitHub for the given ms.
Please try setting it to a high value like 1000 and let me know if this fixes the issue.

**Comment by J-Farmer** [comment]
> requestDelay

Can you expose this as a docker environment variable? I cannot find that file in the filesystem on docker desktop on Windows, and the docker container itself doesn't have a text editor installed for me to edit that specific property.

**Comment by J-Farmer** [comment]
The request delay worked well! I can now see the webpage and projects! 

I'll let you mark as closed in case there is any other discussion that is needed.

**Comment by mkitzmann** [comment]
Glad it works now!

I created a new issue to expose the config as environment variables.

I will close this issue. If anyone still runs into this, feel free to reopen.

**Comment by mkitzmann** [comment]
You could try increasing the request delay even more, but that is just a wild guess.

**Comment by mkitzmann** [comment]
You should be able to add it as an environment variable like:
```
 environment:
      REQUEST_DELAY: 4000
```
